// <auto-generated />
using System;
using DataAccessObject.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessObject.Migrations
{
    [DbContext(typeof(TicketContext))]
    [Migration("20240808070258_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessObject.Entities.Attendee", b =>
                {
                    b.Property<string>("AttendeeId")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CheckInStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("AttendeeId")
                        .HasName("PK_Attendee_1");

                    b.HasIndex("EventId");

                    b.HasIndex("TicketId");

                    b.ToTable("Attendee", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.AttendeeDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .HasColumnType("int");

                    b.Property<string>("AttendeeId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DetailId");

                    b.HasIndex("AttendeeId");

                    b.ToTable("AttendeeDetail", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.Booth", b =>
                {
                    b.Property<int>("BoothId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("BoothId");

                    b.ToTable("Booth", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.BoothRequest", b =>
                {
                    b.Property<int>("BoothRequestId")
                        .HasColumnType("int");

                    b.Property<int>("BoothId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("BoothRequestId");

                    b.HasIndex("BoothId");

                    b.HasIndex("SponsorId");

                    b.ToTable("BoothRequest", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.Gift", b =>
                {
                    b.Property<int>("GiftId")
                        .HasColumnType("int");

                    b.Property<int>("BoothId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("GiftId");

                    b.HasIndex("BoothId");

                    b.ToTable("Gift", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.GiftReception", b =>
                {
                    b.Property<int>("GiftReceptionId")
                        .HasColumnType("int");

                    b.Property<string>("AttendeeId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("GiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceptionDate")
                        .HasColumnType("datetime");

                    b.HasKey("GiftReceptionId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("GiftId");

                    b.ToTable("GiftReception", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("AttendeeId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("PaymentMethod");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("UserRoleEnum")
                        .HasColumnType("int");

                    b.Property<int>("UserStatusEnum")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Venue", (string)null);
                });

            modelBuilder.Entity("DataAccessObject.Entities.Attendee", b =>
                {
                    b.HasOne("DataAccessObject.Entities.Event", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendee_Event");

                    b.HasOne("DataAccessObject.Entities.Ticket", "Ticket")
                        .WithMany("Attendees")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendee_Ticket1");

                    b.Navigation("Event");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DataAccessObject.Entities.AttendeeDetail", b =>
                {
                    b.HasOne("DataAccessObject.Entities.Attendee", "Attendee")
                        .WithMany("AttendeeDetails")
                        .HasForeignKey("AttendeeId")
                        .IsRequired()
                        .HasConstraintName("FK_AttendeeDetail_Attendee");

                    b.Navigation("Attendee");
                });

            modelBuilder.Entity("DataAccessObject.Entities.BoothRequest", b =>
                {
                    b.HasOne("DataAccessObject.Entities.Booth", "Booth")
                        .WithMany("BoothRequests")
                        .HasForeignKey("BoothId")
                        .IsRequired()
                        .HasConstraintName("FK_BoothRequest_Booth");

                    b.HasOne("DataAccessObject.Entities.User", "Sponsor")
                        .WithMany("BoothRequests")
                        .HasForeignKey("SponsorId")
                        .IsRequired()
                        .HasConstraintName("FK_BoothRequest_User");

                    b.Navigation("Booth");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Event", b =>
                {
                    b.HasOne("DataAccessObject.Entities.User", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK_Event_User");

                    b.HasOne("DataAccessObject.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_Event_Venue");

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Gift", b =>
                {
                    b.HasOne("DataAccessObject.Entities.Booth", "Booth")
                        .WithMany("Gifts")
                        .HasForeignKey("BoothId")
                        .IsRequired()
                        .HasConstraintName("FK_Gift_Booth");

                    b.Navigation("Booth");
                });

            modelBuilder.Entity("DataAccessObject.Entities.GiftReception", b =>
                {
                    b.HasOne("DataAccessObject.Entities.Attendee", "Attendee")
                        .WithMany("GiftReceptions")
                        .HasForeignKey("AttendeeId")
                        .IsRequired()
                        .HasConstraintName("FK_GiftReception_Attendee");

                    b.HasOne("DataAccessObject.Entities.Gift", "Gift")
                        .WithMany("GiftReceptions")
                        .HasForeignKey("GiftId")
                        .IsRequired()
                        .HasConstraintName("FK_GiftReception_Gift");

                    b.Navigation("Attendee");

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Transaction", b =>
                {
                    b.HasOne("DataAccessObject.Entities.Attendee", "Attendee")
                        .WithMany("Transactions")
                        .HasForeignKey("AttendeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_Attendee");

                    b.HasOne("DataAccessObject.Entities.Payment", "PaymentMethodNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentMethod")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_Payment");

                    b.Navigation("Attendee");

                    b.Navigation("PaymentMethodNavigation");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Attendee", b =>
                {
                    b.Navigation("AttendeeDetails");

                    b.Navigation("GiftReceptions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Booth", b =>
                {
                    b.Navigation("BoothRequests");

                    b.Navigation("Gifts");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Event", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Gift", b =>
                {
                    b.Navigation("GiftReceptions");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Ticket", b =>
                {
                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("DataAccessObject.Entities.User", b =>
                {
                    b.Navigation("BoothRequests");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("DataAccessObject.Entities.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
